## 4.8 Grouping Data & Aggregating Variables

### This script contains the following points:
#### 1. Import libraries and data
#### 2. Grouping Data
#### 3. Grouping Data w/ Pandas
#### 4. Aggregating Data w/ agg ()
#### 5. Aggregating Data w/ transform ()
#### 6. Deriving Columns w/ loc()
#### 7. Task

# 1. Import Libraries & Data

In [1]:
#import libraries
import pandas as pd
import numpy as np
import os

In [2]:
#create data path
path = r'C:\Users\fa_an\OneDrive\CareerFoundry\Tasks\Data Analytics Immersion\Tasks 4.1-4.10\02_2024 Instacart Basket Analysis'

In [3]:
#import data - ords_prods_merge.pkl as df_ords_prods_merge
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge_derived.pkl'))

In [4]:
#Create a subset
df = ords_prods_merge[:1000000]

In [5]:
#check shape
df.shape

(1000000, 19)

In [6]:
df.head()

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_or_repeat_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_label,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,prior,1,2,8,NaN,First Order,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders
1,2398795,1,prior,2,3,7,15.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Average Orders
2,473747,1,prior,3,3,12,21.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most Orders
3,2254736,1,prior,4,4,7,29.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Average Orders
4,431534,1,prior,5,4,15,28.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most Orders

# 2. Grouping Data w/ Pandas

In [7]:
#use the groupby() function
df.groupby('product_name')

# 4. Aggregating Data w/ agg()

In [8]:
#performing a single aggregation
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [9]:
#aggregating without the use of agg()
df.groupby('department_id')['order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [10]:
#dot notation vs square brackets: aggregating w/out the use of agg()
df.groupby('department_id').order_number.mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [11]:
#peforming multiple aggregations
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

# 5. Aggregating Data w/ transform()

In [12]:
#create a customer loytalty flag using loc()

In [20]:
#split the data into groups based on the 'user_id' column and apply transform 'order_number' to generate max orders per user
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform('max')

In [14]:
ords_prods_merge.head()

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_or_repeat_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_label,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,NaN,First Order,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,10
1,2398795,1,prior,2,3,7,15.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Average Orders,10
2,473747,1,prior,3,3,12,21.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most Orders,10
3,2254736,1,prior,4,4,7,29.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Average Orders,10
4,431534,1,prior,5,4,15,28.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most Orders,10

In [19]:
#check values of new max_order column
ords_prods_merge.head(100)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_or_repeat_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_label,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,NaN,First Order,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,10
1,2398795,1,prior,2,3,7,15.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Average Orders,10
2,473747,1,prior,3,3,12,21.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most Orders,10
3,2254736,1,prior,4,4,7,29.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Average Orders,10
4,431534,1,prior,5,4,15,28.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most Orders,10
5,3367565,1,prior,6,2,7,19.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,10
6,550135,1,prior,7,1,9,20.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,10
7,3108588,1,prior,8,1,14,14.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,10
8,2295261,1,prior,9,1,16,0.0,Repeat Order,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,10
9,2550362,1,prior,10,4,8,30.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Average Orders,10
10,2968173,15,prior,15,1,9,7.0,Repeat Order,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,22
11,1870022,15,prior,17,2,16,8.0,Repeat Order,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,22
12,1911383,15,prior,18,2,11,7.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,22
13,2715276,15,prior,21,1,9,7.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,22
14,487368,15,prior,22,1,10,14.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,22
15,2293453,19,prior,2,5,14,6.0,Repeat Order,196,3,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,9
16,1973799,19,prior,5,6,12,8.0,Repeat Order,196,15,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,9
17,532817,19,prior,7,4,17,6.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Average Orders,9
18,1573906,21,prior,10,3,10,6.0,Repeat Order,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most Orders,33
19,1593000,31,prior,10,3,8,7.0,Repeat Order,196,17,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Average Orders,20
20,2231262,31,prior,17,3,11,8.0,Repeat Order,196,14,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most Orders,20
21,2580647,43,prior,6,4,16,4.0,Repeat Order,196,9,0,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most Orders,11
22,2187180,43,prior,9,4,12,3.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most Orders,11
23,2497897,52,prior,1,1,9,NaN,First Order,196,4,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,27
24,1318871,52,prior,2,1,10,7.0,Repeat Order,196,5,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,27
25,1261384,52,prior,3,1,10,7.0,Repeat Order,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,27
26,580568,52,prior,5,2,10,8.0,Repeat Order,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,27
27,2428073,52,prior,7,2,7,8.0,Repeat Order,196,5,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,27
28,342306,52,prior,9,1,11,7.0,Repeat Order,196,5,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,27
29,1520353,52,prior,10,2,10,8.0,Repeat Order,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,27
30,2542086,52,prior,11,2,9,7.0,Repeat Order,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,27
31,944694,52,prior,12,1,16,6.0,Repeat Order,196,7,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,27
32,1268191,52,prior,15,2,11,8.0,Repeat Order,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,27
33,1122089,52,prior,17,2,10,6.0,Repeat Order,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,27
34,1498922,52,prior,18,2,10,14.0,Repeat Order,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,27
35,180919,52,prior,19,3,8,8.0,Repeat Order,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Average Orders,27
36,2695875,52,prior,21,5,10,30.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,27
37,3205960,67,prior,1,3,11,NaN,First Order,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most Orders,24
38,970922,67,prior,2,1,15,5.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,24
39,596585,67,prior,3,1,13,7.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,24
40,2037087,67,prior,4,2,9,8.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,24
41,2474111,67,prior,5,3,14,8.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most Orders,24
42,1568481,67,prior,6,3,12,7.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most Orders,24
43,2048527,67,prior,8,2,11,7.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,24
44,2389031,67,prior,9,2,14,7.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,24
45,2378562,67,prior,10,1,10,6.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,24
46,1515698,67,prior,11,1,11,7.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,24
47,1928050,67,prior,12,2,12,8.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,24
48,1949274,67,prior,13,1,10,6.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,24
49,551869,67,prior,14,1,9,7.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,24
50,768572,67,prior,16,4,10,9.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most Orders,24
51,150528,67,prior,18,5,16,4.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,24
52,29758,67,prior,19,0,14,9.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Busiest day,Busiest days,Most Orders,24
53,1558976,67,prior,21,1,9,5.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,24
54,863974,67,prior,22,1,11,14.0,Repeat Order,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,24
55,2308399,67,prior,23,1,14,14.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,24
56,2759128,81,prior,3,1,9,14.0,Repeat Order,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,7
57,1812985,81,prior,5,2,20,30.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,7
58,1889835,82,prior,1,3,15,NaN,First Order,196,6,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most Orders,19
59,499460,82,prior,3,5,10,5.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,19
60,2728456,82,prior,4,0,11,16.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Busiest day,Busiest days,Most Orders,19
61,2653743,82,prior,6,4,9,13.0,Repeat Order,196,5,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most Orders,19
62,1358880,82,prior,9,1,10,30.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,19
63,343588,82,prior,10,2,11,1.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,19
64,3034663,82,prior,15,2,11,12.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,19
65,147262,82,prior,18,1,13,7.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,19
66,3144004,82,prior,19,2,15,8.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,19
67,2126069,98,prior,3,0,9,25.0,Repeat Order,196,7,0,Soda,77,7,9.0,Mid-range product,Busiest day,Busiest days,Most Orders,14
68,2210120,98,prior,7,5,14,5.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,14
69,681011,98,prior,9,3,9,30.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most Orders,14
70,2846344,98,prior,11,4,13,15.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most Orders,14
71,747431,98,prior,12,6,13,30.0,Repeat Order,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,14
72,2383054,98,prior,13,4,11,30.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most Orders,14
73,1993729,98,prior,14,5,8,8.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,14
74,1403849,109,prior,3,3,17,9.0,Repeat Order,196,5,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Average Orders,6
75,520620,120,prior,1,3,11,NaN,First Order,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most Orders,3
76,3273029,120,prior,3,2,8,19.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,3
77,1861943,185,prior,2,1,12,25.0,Repeat Order,196,10,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,6
78,2040988,195,prior,1,1,14,NaN,First Order,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,58
79,1680569,195,prior,8,1,9,4.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,58
80,276171,195,prior,19,5,11,3.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,58
81,2744976,195,prior,22,5,10,7.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,58
82,2781919,195,prior,25,1,14,4.0,Repeat Order,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most Orders,58
83,1738718,195,prior,31,2,8,4.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,58
84,3058369,195,prior,34,3,10,6.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most Orders,58
85,1485596,195,prior,37,2,15,0.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,58
86,417035,195,prior,40,3,16,2.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most Orders,58
87,1615297,195,prior,47,5,10,2.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,58
88,1765587,195,prior,52,3,12,2.0,Repeat Order,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most Orders,58
89,745908,195,prior,57,4,11,3.0,Repeat Order,196,3,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most Orders,58
90,2505656,222,prior,17,2,12,1.0,Repeat Order,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,70
91,3268370,222,prior,38,5,15,1.0,Repeat Order,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,70
92,2016711,290,prior,9,5,19,6.0,Repeat Order,196,8,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,51
93,2706088,290,prior,28,6,10,7.0,Repeat Order,196,16,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,51
94,1952286,331,prior,6,5,16,30.0,Repeat Order,196,8,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,8
95,3226575,360,prior,1,5,12,NaN,First Order,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,3
96,1469869,377,prior,3,5,17,3.0,Repeat Order,196,9,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,3
97,1927023,387,prior,2,4,10,22.0,Repeat Order,196,3,0,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most Orders,8
98,858092,420,prior,4,1,19,30.0,Repeat Order,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Average Orders,22
99,119314,420,prior,5,3,19,16.0,Repeat Order,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Average Orders,22

# 6. Deriving Columns w/ loc()

In [21]:
#create a "loyalty" flag based on the max_order column
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal Customer'

In [22]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] > 10) & (ords_prods_merge['max_order'] <= 40), 'loyalty_flag'] = 'Regular Customer'

In [24]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New Customer'

In [25]:
#check frequency of new column 'loyalty_flag'
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular Customer    15876776
Loyal Customer      10284093
New Customer         6243990
Name: count, dtype: int64

In [26]:
#first 60 rows of df using user_id,loyalty_flag, and order_number
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New Customer             1
1         1      New Customer             2
2         1      New Customer             3
3         1      New Customer             4
4         1      New Customer             5
5         1      New Customer             6
6         1      New Customer             7
7         1      New Customer             8
8         1      New Customer             9
9         1      New Customer            10
10       15  Regular Customer            15
11       15  Regular Customer            17
12       15  Regular Customer            18
13       15  Regular Customer            21
14       15  Regular Customer            22
15       19      New Customer             2
16       19      New Customer             5
17       19      New Customer             7
18       21  Regular Customer            10
19       31  Regular Customer            10
20       31  Regular Customer            17
21       43  Regular Customer             6
22       43  Regular Customer             9
23       52  Regular Customer             1
24       52  Regular Customer             2
25       52  Regular Customer             3
26       52  Regular Customer             5
27       52  Regular Customer             7
28       52  Regular Customer             9
29       52  Regular Customer            10
30       52  Regular Customer            11
31       52  Regular Customer            12
32       52  Regular Customer            15
33       52  Regular Customer            17
34       52  Regular Customer            18
35       52  Regular Customer            19
36       52  Regular Customer            21
37       67  Regular Customer             1
38       67  Regular Customer             2
39       67  Regular Customer             3
40       67  Regular Customer             4
41       67  Regular Customer             5
42       67  Regular Customer             6
43       67  Regular Customer             8
44       67  Regular Customer             9
45       67  Regular Customer            10
46       67  Regular Customer            11
47       67  Regular Customer            12
48       67  Regular Customer            13
49       67  Regular Customer            14
50       67  Regular Customer            16
51       67  Regular Customer            18
52       67  Regular Customer            19
53       67  Regular Customer            21
54       67  Regular Customer            22
55       67  Regular Customer            23
56       81      New Customer             3
57       81      New Customer             5
58       82  Regular Customer             1
59       82  Regular Customer             3